name: Deploy to Azure Container Registry

on: [push, workflow_dispatch]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@main
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push image
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_CR_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_CR_USERNAME }}
        password: ${{ secrets.AZURE_CR_PASSWORD }}
    - name: Build and push image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.AZURE_CR_IMAGE_NAME }}:latest
    
  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main
      - name: Read ssh key
        run: echo "${{ secrets.AZURE_VM_SSH_KEY }}" > key.pem
      - name: Update key permissions
        run: chmod 400 key.pem
      - name: Stop container
        run: ssh -i key -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }} 'docker-compose -f /opt/server-composed/todoapp/docker-compose.yaml down -v'
      - name: Restart container
        run: ssh -i key -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }} 'docker pull ${{ secrets.AZURE_CR_IMAGE_NAME }}:latest && docker-compose -f /opt/server-composed/todoapp/docker-compose.yaml up -d'
