name: Deploy to Azure VM

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Set up jdk 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: adopt
    - name: Build with maven
      run: mvn --batch-mode package --file pom.xml
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Read ssh key
      run: echo "${{ secrets.AZURE_VM_SSH_KEY }}" > key.pem
    - name: Update key permissions
      run: chmod 400 key.pem
    - name: Copy file to vm
      run: scp -i key.pem -o StrictHostKeyChecking=no target/todo-app-0.0.1-SNAPSHOT.jar ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }}:/opt/server/todoapp/
    - name: Restart app
      run: ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }} "sudo systemctl restart todoapp"
