name: Deploy to Azure App Service

# on: [push, workflow_dispatch]
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: adopt
    - name: Build with Maven
      run: mvn --batch-mode package --file pom.xml
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ds-todo-app
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: target/*.jar
